#version 450

#include "cubeUtil.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 6) in;


layout(set = 0, binding = 0) uniform samplerCube inputImageCube;
layout(set = 1, binding = 0) buffer OutputBuffer
{
    float data[];
};

layout(push_constant) uniform PushConstants {
	float roughness;
	uint faceSize;
	uint numOfSamples;
	uint mipmapLevel;
};

vec3 PrefilterEnvMap(float Roughness, vec3 R) {
	vec3 N = R;
	vec3 V = R;

	vec3 prefilteredColor = vec3(0, 0, 0);
	float totalWeight = 0.0;
	for (uint i = 0; i < numOfSamples; i++) {
		vec2 Xi = Hammersley(i, numOfSamples);
		vec3 H = importanceSampleGGX(Xi, Roughness, N);
		vec3 L = 2 * dot(V, H) * H - V;

		float NoL = clamp(dot(N, L), 0, 1);
		if (NoL > 0) {
			prefilteredColor += texture(inputImageCube, L).rgb * NoL;
			totalWeight += NoL;
		}
	}
	return prefilteredColor / totalWeight;
}

vec3 computeDirection(uint faceId, float u, float v) {
	switch (faceId) {
	case 0: return normalize(vec3(1, u, -v));
	case 1: return normalize(vec3(-1, u, v));
	case 2: return normalize(vec3(v, 1, u));
	case 3: return normalize(vec3(v, -1, -u));
	case 4: return normalize(vec3(v, -u, 1));
	case 5: return normalize(vec3(-v, -u, -1));	
	default: return vec3(0.0);
	}
}


void main() {
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

	if (pixel.x >= faceSize || pixel.y >= faceSize) {
		return;
	}

	uint faceId = gl_LocalInvocationID.z;

	vec2 uv = ((pixel + 0.5) / faceSize) * 2.0 - 1.0;

	vec3 R = computeDirection(faceId, uv.x, uv.y);

	vec3 color = PrefilterEnvMap(roughness, R);

	uint index = ((faceId * faceSize + pixel.x) * faceSize + pixel.y) * 3;

	data[index + 0] = color.r;
	data[index + 1] = color.g;
	data[index + 2] = color.b;
}

