#version 450
#extension GL_EXT_debug_printf : enable

#include "AVBD-header.glsl"

layout(local_size_x = 8, local_size_y = 1, local_size_z = 1) in;

void graph_color(uint id) {

	for (uint i = 0; i < rigidbodyCount; i++) {
		uint rid = i;
		uint occupied_mask = 0;
		int cur = rigids[rid].listHead;
		while (cur != -1) {
			int color = colors[manifolds[cur].force.bodyB];
			if (manifolds[cur].numContacts != 0 && color < 32) {
				occupied_mask |= (1u << color);
			}
			
			cur = manifolds[cur].force.next;
		}
        //debugPrintfEXT("color = %d", int(findLSB(~occupied_mask)));
        colors[rid] = int(findLSB(~occupied_mask));
		
	}	
}

void main() {
   
	
    uint id = gl_GlobalInvocationID.x;
	
	if (id * 16 >= rigidbodyCount) {
		return;
	}
	if (id != 0) {
		return;
	}
	graph_color(id);
    

}
