#version 450
#extension GL_EXT_debug_printf : enable

#include "AVBD-header.glsl"
layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

void main() {
	uint id = gl_GlobalInvocationID.x;

	if (id >= rigidbodyCount || rigids[id].isStatic == 1 || colors[id] != color) {
		return;
	}

	rigids[id].positionLin = updatedRigids[id].positionLin;
	rigids[id].positionAng = updatedRigids[id].positionAng;		
	if (id == 0) {
		//debugPrintfEXT("main-loop: updatedpositionLin %f %f %f", updatedRigids[id].positionLin.x, updatedRigids[id].positionLin.y, updatedRigids[id].positionLin.z);
	}
}
