#version 450


#include "AVBD-header.glsl"

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

vec3 rotate(vec4 angle, vec3 v) {
	vec3 u = vec3( angle.x, angle.y, angle.z );
	vec3 t = cross(u, v) * 2.0f;
	return v + t * angle.w + cross(u, t);
}

OBB makeOBB(uint body) {
	OBB box;
	box.center = rigids[body].positionLin;
	box.rotation = rigids[body].positionAng;
	box.halfExtent = rigids[body].size * 0.5f;
	box.axis[0] = rotate(rigids[body].positionAng, vec3( 1.0f, 0.0f, 0.0f ));
	box.axis[1] = rotate(rigids[body].positionAng, vec3( 0.0f, 1.0f, 0.0f ));
	box.axis[2] = rotate(rigids[body].positionAng, vec3( 0.0f, 0.0f, 1.0f ));
	return box;
}

vec4 conjugate(vec4 q) {
	return vec4( -q.x, -q.y, -q.z, q.w );
}


vec3 transform(vec3 qLin, vec4 qAng, vec3 v) {
	return rotate(qAng, v) + qLin;
}

vec4 inverse(vec4 q) {
	return conjugate(q) / dot(q, q);
}


vec4 quatTime(vec4 a, vec4 b) {
	return vec4(
		a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
		a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
		a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
		a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z );
}


vec4 addAng(vec4 a, vec3 b) {
	return normalize(a + quatTime(vec4( b.x, b.y, b.z, 0), a) * 0.5f);
}

vec3 subAng(vec4 a, vec4 b) {
	return quatTime(a, inverse(b)).xyz * 2.0f;
}

void updateDual(uint index, float alpha) {
 uint a = manifolds[index].force.bodyA, b = manifolds[index].force.bodyB;
 vec3 dLin = (rigids[a].positionLin-rigids[a].initialLin)-(rigids[b].positionLin-rigids[b].initialLin);
 vec3 da = subAng(rigids[a].positionAng,rigids[a].initialAng);
 vec3 db = subAng(rigids[b].positionAng,rigids[b].initialAng);
 mat3 basis = manifolds[index].basis;
 float friction = manifolds[index].friction;
 for (uint i = 0; i < manifolds[index].numContacts; ++i) {
  Contact c = manifolds[index].contacts[i];
  vec3 ra = rotate(rigids[a].positionAng,c.rA), rb = rotate(rigids[b].positionAng,c.rB);
  vec3 C = c.C0*(1-alpha)+transpose(basis)*(dLin+cross(da,ra)-cross(db,rb));
  vec3 F = c.penalty*C+c.lambda;
  F.x = min(F.x,0);
  float bounds = abs(F.x)*friction, tangential = length(F.yz);
  if (tangential > bounds && tangential > 0) F.yz *= bounds/tangential;
  if (F.x < 0) c.penalty.x = min(c.penalty.x+betaLin*abs(C.x),PENALTY_MAX);
  if (tangential <= bounds) {
   c.penalty.yz = min(c.penalty.yz+betaLin*abs(C.yz),vec2(PENALTY_MAX));
   c.stick = length(C.yz) < STICK_THRESH;
  }
  manifolds[index].contacts[i].lambda = F;
  manifolds[index].contacts[i].penalty = c.penalty;
  manifolds[index].contacts[i].stick = c.stick;
 }
}

void main() {
	uint id = gl_GlobalInvocationID.x;

	if (id >= activeCount) {
		return;
	}

	updateDual(uint(scratch[activeOffset() + id]), alpha);
}
