#version 450
#extension GL_EXT_debug_printf : enable

#include "AVBD-header.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

vec3 rotate(vec4 angle, vec3 v) {
	vec3 u = vec3( angle.x, angle.y, angle.z );
	vec3 t = cross(u, v) * 2.0f;
	return v + t * angle.w + cross(u, t);
}

OBB makeOBB(uint body) {
	OBB box;
	box.center = rigids[body].positionLin;
	box.rotation = rigids[body].positionAng;
	box.halfExtent = rigids[body].size * 0.5f;
	box.axis[0] = rotate(rigids[body].positionAng, vec3( 1.0f, 0.0f, 0.0f ));
	box.axis[1] = rotate(rigids[body].positionAng, vec3( 0.0f, 1.0f, 0.0f ));
	box.axis[2] = rotate(rigids[body].positionAng, vec3( 0.0f, 0.0f, 1.0f ));
	return box;
}

vec4 conjugate(vec4 q) {
	return vec4( -q.x, -q.y, -q.z, q.w );
}


vec3 transform(vec3 qLin, vec4 qAng, vec3 v) {
	return rotate(qAng, v) + qLin;
}

vec4 inverse(vec4 q) {
	return conjugate(q) / dot(q, q);
}


vec4 quatTime(vec4 a, vec4 b) {
	return vec4(
		a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
		a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
		a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
		a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z );
}


vec4 addAng(vec4 a, vec3 b) {
	return normalize(a + quatTime(vec4( b.x, b.y, b.z, 0), a) * 0.5f);
}

vec3 subAng(vec4 a, vec4 b) {
	return quatTime(a, inverse(b)).xyz * 2.0f;
}

void updateDual(uint manifoldIndex, float alpha)
{
	vec3 dqALin = rigids[manifolds[manifoldIndex].force.bodyA].positionLin - rigids[manifolds[manifoldIndex].force.bodyA].initialLin;
	vec3 dqAAng = subAng(rigids[manifolds[manifoldIndex].force.bodyA].positionAng, rigids[manifolds[manifoldIndex].force.bodyA].initialAng);
	vec3 dqBLin = rigids[manifolds[manifoldIndex].force.bodyB].positionLin - rigids[manifolds[manifoldIndex].force.bodyB].initialLin;
	vec3 dqBAng = subAng(rigids[manifolds[manifoldIndex].force.bodyB].positionAng, rigids[manifolds[manifoldIndex].force.bodyB].initialAng);

	for (int i = 0; i < manifolds[manifoldIndex].numContacts; i++) {
		vec3 rAWorld = rotate(rigids[manifolds[manifoldIndex].force.bodyA].positionAng, manifolds[manifoldIndex].contacts[i].rA);
		vec3 rBWorld = rotate(rigids[manifolds[manifoldIndex].force.bodyB].positionAng, manifolds[manifoldIndex].contacts[i].rB);

		mat3 jALin = manifolds[manifoldIndex].basis;
		mat3 jBLin = -manifolds[manifoldIndex].basis;
		
		mat3 jAAng = transpose(mat3(cross(rAWorld, jALin[0]), cross(rAWorld, jALin[1]), cross(rAWorld, jALin[2])));
		mat3 jBAng = transpose(mat3(cross(rBWorld, jBLin[0]), cross(rBWorld, jBLin[1]), cross(rBWorld, jBLin[2])));

		jALin = transpose(jALin);
		jBLin = transpose(jBLin);
		
		mat3 K = mat3(
			vec3(manifolds[manifoldIndex].contacts[i].penalty.x, 0.0, 0.0),
			vec3(0.0, manifolds[manifoldIndex].contacts[i].penalty.y, 0.0),
			vec3(0.0, 0.0, manifolds[manifoldIndex].contacts[i].penalty.z)
		);
		vec3 C = manifolds[manifoldIndex].contacts[i].C0 * (1 - alpha) + jALin * dqALin + jBLin * dqBLin + jAAng * dqAAng + jBAng * dqBAng;

		vec3 F = K * C + manifolds[manifoldIndex].contacts[i].lambda;

		F.x = min(F.x, 0.0f);

		float bounds = abs(F.x) * manifolds[manifoldIndex].friction;
		float frictionScale = length(vec2( F.y, F.z ));
		if (frictionScale > bounds && frictionScale > 0) {
			F.y *= bounds / frictionScale;
			F.z *= bounds / frictionScale;
		}

		manifolds[manifoldIndex].contacts[i].lambda = F;

		if (F.x < 0)
			manifolds[manifoldIndex].contacts[i].penalty[0] = min(manifolds[manifoldIndex].contacts[i].penalty[0] + betaLin * abs(C.x), PENALTY_MAX);
		if (frictionScale <= bounds) {
			manifolds[manifoldIndex].contacts[i].penalty[1] = min(manifolds[manifoldIndex].contacts[i].penalty[1] + betaLin * abs(C.y), PENALTY_MAX);
			manifolds[manifoldIndex].contacts[i].penalty[2] = min(manifolds[manifoldIndex].contacts[i].penalty[2] + betaLin * abs(C.z), PENALTY_MAX);
			manifolds[manifoldIndex].contacts[i].stick = length(vec2(C.y, C.z)) < STICK_THRESH;
		}
	}
}



void main() {
	uint id = gl_GlobalInvocationID.x;

	if (id >= globalManifoldCount) {
		return;
	}

	updateDual(id, alpha);
	//debugPrintfEXT("dual %d", id);
}
