#version 450
#include "AVBD-header.glsl"
layout(local_size_x = 128) in;
vec4 inverse(vec4 q) { return vec4(-q.xyz,q.w) / dot(q,q); }
vec4 quatTime(vec4 a, vec4 b) {
	return vec4(
		a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
		a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
		a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
		a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z );
}



vec4 addAng(vec4 a, vec3 b) {
	return normalize(a + quatTime(vec4( b.x, b.y, b.z, 0 ), a) * 0.5f);
}

vec3 subAng(vec4 a, vec4 b) {
	return quatTime(a, inverse(b)).xyz * 2.0f;
}


void main() {
	uint id = gl_GlobalInvocationID.x;
	
	if (id < rigidbodyCount) {
		//if (id == 0)
		//	debugPrintfEXT("position = %f %f %f isStatic%d\n", rigids[id].positionLin.x, rigids[id].positionLin.y, rigids[id].positionLin.z, rigids[id].isStatic);
		rigids[id].inertialLin = rigids[id].positionLin + rigids[id].velocityLin * dt;
		if (rigids[id].isStatic == 0) {
			rigids[id].inertialLin += vec3(0.0, gravity, 0.0) * (dt * dt);
		}
		rigids[id].inertialAng = addAng(rigids[id].positionAng, rigids[id].velocityAng * dt);

		vec3 accel = (rigids[id].velocityLin - rigids[id].prevVelocityLin) / dt;
		
		float accelExt = accel.y * sign(gravity);

		float accelWeight = clamp(accelExt / abs(gravity), 0.0, 1.0);
	
		if (isinf(accelWeight) || isnan(accelWeight)) {
			accelWeight = 0.0;
		}
	
		rigids[id].initialLin = rigids[id].positionLin;
		rigids[id].initialAng = rigids[id].positionAng;

		if (rigids[id].isStatic == 0) {
		
			rigids[id].positionLin = rigids[id].positionLin + rigids[id].velocityLin * dt + vec3(0.0, gravity, 0.0) * (accelWeight * dt * dt);
			rigids[id].positionAng = addAng(rigids[id].positionAng, rigids[id].velocityAng * dt);
		}
	}

}
