#version 450


#include "AVBD-header.glsl"

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

vec4 conjugate(vec4 q) {
	return vec4( -q.x, -q.y, -q.z, q.w );
}

vec4 inverse(vec4 q) {
	return conjugate(q) / dot(q, q);
}


vec4 quatTime(vec4 a, vec4 b) {
	return vec4(
		a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
		a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
		a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
		a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z );
}



vec3 subAng(vec4 a, vec4 b) {
	return quatTime(a, inverse(b)).xyz * 2.0f;
}

void main() {
	uint id = gl_GlobalInvocationID.x;

	if (id >= rigidbodyCount) {
		return;
	}

 if (colors[id] < 0 && rigids[id].isStatic == 0) atomicOr(errors, 2u);
 if (any(isnan(rigids[id].positionLin)) || any(isinf(rigids[id].positionLin)) || any(isnan(rigids[id].positionAng)) || any(isinf(rigids[id].positionAng))) atomicOr(errors, 4u);
	rigids[id].prevVelocityLin = rigids[id].velocityLin;
	if (rigids[id].isStatic == 0) {
		rigids[id].velocityLin = (rigids[id].positionLin - rigids[id].initialLin) / dt;
		rigids[id].velocityAng = subAng(rigids[id].positionAng,rigids[id].initialAng) / dt;
	}
   

}
